Basic x112virtgpu support
AsahiLinux/muvm pull request #72
Opened 2024-10-03 12:09 UTC by asahilina

Replace the trivial X11 socket passthrough with x112virtgpu, if it is installed and DAX is enabled. This lives alongside the existing sommelier solution, so we can test both options for now.

2024-10-03 22:10 UTC, alyssarosenzweig approved these changes

2024-10-04 09:12 UTC, slp requested changes
Small change requested. Also, please add a SoB to the second commit.

2024-10-26 17:00 UTC, asahilina commented
Removed the DAX check and snuck in some Clippy fixes in related code.

This now soft-depends on #96. They can be merged in any order, but x112virtgpu will only work as intended if #96 is also merged.

2024-10-29 21:29 UTC, alyssarosenzweig approved these changes
les go

2024-10-30 14:51 UTC, asahilina commented
Added another commit to make this mutually exclusive with sommelier, and enabled with the `--direct-x11` option. This makes it less confusing to test, and there's no real reason to aim to support sommelier+this simultaneously long term.

2024-10-30 14:55 UTC, teohhanhui commented on crates/muvm/src/cli_options.rs
> +        .flag(true, false);
```suggestion
        .switch();
```

https://docs.rs/bpaf/latest/bpaf/parsers/struct.NamedArg.html#method.switch

2024-10-30 16:41 UTC, asahilina commented on crates/muvm/src/cli_options.rs
> +        .flag(true, false);
Fixed, thanks!

2024-10-30 16:45 UTC, teohhanhui approved these changes

2024-10-30 16:58 UTC, slp approved these changes

2024-10-30 16:58 UTC, merged