muvm-guest: Reopen the system tty (hvc0)
AsahiLinux/muvm pull request #88
Opened 2024-10-15 16:18 UTC by asahilina

This fixes the classic:

-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell

I'm not entirely sure why this doesn't happen with our main shell, but it happens with things like sudo. (There are a bunch of other things needed to make sudo work, of course)

2024-10-16 11:29 UTC, alyssarosenzweig approved these changes

2024-10-16 11:31 UTC, teohhanhui commented on crates/muvm/src/guest/bin/muvm-guest.rs
> +use rustix::fd::AsFd;
This is just a [re-export](https://docs.rs/rustix/latest/rustix/fd/trait.AsFd.html) of [`std::os::fd::AsFd`](https://doc.rust-lang.org/std/os/fd/trait.AsFd.html)

2024-10-16 12:29 UTC, slp requested changes
LGTM once the issue pointed by @teohhanhui is addressed.

2024-10-26 16:46 UTC, asahilina commented
Fixed.

2024-10-28 09:52 UTC, slp approved these changes

2024-10-28 09:52 UTC, merged